### PR TITLE
Show total mc count

### LINKED ISSUE #162: Display current total number of MCs in timetable
Have to take into account that FYP modules are 12 MCs on paper but only 6 MCs per semester. Can possibly maintain a list of FYP module codes and check against it when calculating.

### PR DESCRIPTION
**Pull request by yangshun**
Added on to @tgxworld 's #185 . @xinan @xbili please review (:
Closes #162 

screen shot 2015-03-29 at 12 40 42 am

### CODE REVIEW

**Comment by xinan** [comment]
Looks quite good. Shall we change the colour of the last row on dark theme? Currently it looks like:

total-mc-screenshot-dark

**Comment by tgxworld** [comment]
I think the dissertation module should show `6` instead of `12` Otherwise, it'll really be confusing when people add up the column and see something different,

**Comment by yangshun** [comment]
@tgxworld true, but in the transcript or MyISIS, it shows the total MCs for that module regardless of whether it spans across multiple semesters. I think we should follow that for consistency.

**Comment by tgxworld** [comment]
Do we have a disclaimer that we're not liable for any mistakes in the counting of MCs? Just in case.

**Comment by yangshun** [comment]
We'll come up with a Terms of Service soon. Put our IS1103FC knowledge to good use @xbili  lol

**Comment by xbili** [comment]
@yangshun Yup that sounds good. I think a bit more effort can be put to make it more readable as well. We care about our users 👍

**Pull request merged**
