### PR TITLE
#181 Add white colour theme

### PR DESCRIPTION
**Pull request by xming13**
Currently there is a theme called 'Green Screen' so I am just following the naming for consistency. Personally I prefer to name it 'White' instead :smile:

### CODE REVIEW

**Comment by yangshun** [comment]
Hehe thanks @xming13 !

**Comment by yangshun** [comment]
In future you can add `Closes #181` to your commit message or comment and it will close the issue mentioned when the PR is merged.

**Comment by xming13** [comment]
Wow cool! I didn't know that

**Comment by tgxworld** [comment]
There are a whole bunch of keywords to choose from :smile: https://help.github.com/articles/closing-issues-via-commit-messages/

**Comment by xming13** [comment]
Thanks for the info @tgxworld ! :smile:

**Pull request merged**
