### PR TITLE
Update venues

### LINKED ISSUE #2506: Venue data update for LAW_CR3-5
- Room Name: LAW CR3-5
- Floor: 3
- Location: [1.3189643800229218, 103.81700009107591](https://www.openstreetmap.org/?mlat=1.3189643800229218&mlon=103.81700009107591#map=19/1.3189643800229218/103.81700009107591)

**Venue does not exist in current version**

**Update proposed:**

```json
"LAW_CR3-5": {
  "roomName": "LAW CR3-5",
  "floor": 3,
  "location": {
    "x": 103.81700009107591,
    "y": 1.3189643800229218
  }
}
```

### LINKED ISSUE #2554: Venue data update for LAW_SR5-4
- Room Name: SR 5 - 4
- Floor: 5
- Location: [1.3186839958358212, 103.81657764315605](https://www.openstreetmap.org/?mlat=1.3186839958358212&mlon=103.81657764315605#map=19/1.3186839958358212/103.81657764315605)

**Venue does not exist in current version**

**Update proposed:**

```json
"LAW_SR5-4": {
  "roomName": "SR 5 - 4",
  "floor": 5,
  "location": {
    "x": 103.81657764315605,
    "y": 1.3186839958358212
  }
}
```

### LINKED ISSUE #2564: Venue data update for Frontier
- Room Name: Frontier
- Floor: 1
- Location: [1.296364945076005, 103.78003966445547](https://www.openstreetmap.org/?mlat=1.296364945076005&mlon=103.78003966445547#map=19/1.296364945076005/103.78003966445547)

**Venue does not exist in current version**

**Update proposed:**

```json
"Frontier": {
  "roomName": "Frontier",
  "floor": 1,
  "location": {
    "x": 103.78003966445547,
    "y": 1.296364945076005
  }
}
```

### LINKED ISSUE #2565: Venue data update for S8-0402
- Room Name: S8-0402
- Floor: 4
- Location: [1.296072323916885, 103.77937403740883](https://www.openstreetmap.org/?mlat=1.296072323916885&mlon=103.77937403740883#map=19/1.296072323916885/103.77937403740883)

**Venue does not exist in current version**

**Update proposed:**

```json
"S8-0402": {
  "roomName": "S8-0402",
  "floor": 4,
  "location": {
    "x": 103.77937403740883,
    "y": 1.296072323916885
  }
}
```

### LINKED ISSUE #2578: Venue data update for TP-SR2
- Room Name: Town Plaza Seminar Room 2
- Floor: 2
- Location: [1.3040132389563945, 103.77344010473281](https://www.openstreetmap.org/?mlat=1.3040132389563945&mlon=103.77344010473281#map=19/1.3040132389563945/103.77344010473281)

**Venue does not exist in current version**

**Update proposed:**

```json
"TP-SR2": {
  "roomName": "Town Plaza Seminar Room 2",
  "floor": 2,
  "location": {
    "x": 103.77344010473281,
    "y": 1.3040132389563945
  }
}
```

### LINKED ISSUE #2603: Venue data update for LAW_CR2-1
- Room Name: CR 2-1
- Floor: 2
- Location: [1.3187050325808396, 103.81667928422443](https://www.openstreetmap.org/?mlat=1.3187050325808396&mlon=103.81667928422443#map=19/1.3187050325808396/103.81667928422443)

**Venue does not exist in current version**

**Update proposed:**

```json
"LAW_CR2-1": {
  "roomName": "CR 2-1",
  "floor": 2,
  "location": {
    "x": 103.81667928422443,
    "y": 1.3187050325808396
  }
}
```

### LINKED ISSUE #2604: Venue data update for LAW_CR2-2
- Room Name: CR2-2
- Floor: 2
- Location: [1.3187506180542539, 103.81671683479652](https://www.openstreetmap.org/?mlat=1.3187506180542539&mlon=103.81671683479652#map=19/1.3187506180542539/103.81671683479652)

**Venue does not exist in current version**

**Update proposed:**

```json
"LAW_CR2-2": {
  "roomName": "CR2-2",
  "floor": 2,
  "location": {
    "x": 103.81671683479652,
    "y": 1.3187506180542539
  }
}
```

### LINKED ISSUE #2606: Venue data update for TP-SR2
- Room Name: TP-SR2
- Floor: 2
- Location: [1.3038567726300767, 103.77355339315676](https://www.openstreetmap.org/?mlat=1.3038567726300767&mlon=103.77355339315676#map=19/1.3038567726300767/103.77355339315676)

**Venue does not exist in current version**

**Update proposed:**

```json
"TP-SR2": {
  "roomName": "TP-SR2",
  "floor": 2,
  "location": {
    "x": 103.77355339315676,
    "y": 1.3038567726300767
  }
}
```

### PR DESCRIPTION
**Pull request by shimeilee**
## Context

Closes #2506 - LAW_CR3-5
Closes #2554 - LAW_SR5-4
Closes #2564 - Frontier
Closes #2565 - S8-0402
Closes #2578 - TP-SR2
Closes #2603 - LAW_CR2-1
Closes #2604 - LAW_CR2-2
Closes #2606 - TP-SR2

## Implementation

I did not include issues #2514, #2566 as the venue of E5-04-1819 and S7-0401 do not seem right.

### CODE REVIEW

**Comment by ZhangYiJiang** [comment]
There seems to be other changes in this PR that are not from issues, eg. LT18's location has changed incorrectly https://5eb80dc81842f5cad80a5aba--nusmods-deploy-preview.netlify.app/venues/LT18?q=lt18&localVenue=1. Where did these changes come from?

**Comment by shimeilee** [comment]
> There seems to be other changes in this PR that are not from issues, eg. LT18's location has changed incorrectly https://5eb80dc81842f5cad80a5aba--nusmods-deploy-preview.netlify.app/venues/LT18?q=lt18&localVenue=1. Where did these changes come from?

I ran `update-venues.js` before running `download-location-updates.js` in the previous commit. LT18's coordinates were affected because `update-venues.js` checks if the remote data (NUSVenues) is more accurate than the local data in `venues.json`, and updates it to the remote data's values.

Moving forward, since the venue updates could be attained from`download-location-updates.js`, should we remove `update-venues.js` as it does not seem to be used?

**Comment by ZhangYiJiang** [comment]
Oh, you don't need to run `update-venues` - that script exists in the hope that NUS would update their data but at this point that seems very unlikely, so we should probably just delete it. You can rollback changes from that script - we should trust local now

**Comment by shimeilee** [comment]
Yup I've rollback the changes from that script by rebasing that commit. Hope that is alright! 

Shall I create a PR to remove that script (for tracking purposes), or shall I rename this PR to better reflect the update of venues + script removal? Any preference?

**Comment by ZhangYiJiang** [comment]
Separate PR please, and thanks

**Pull request merged**
