### PR TITLE
Add npm-debug.log into gitignore

### PR DESCRIPTION
**Pull request by yangshun**
:smile_cat:

### CODE REVIEW

**Comment by xbili** [comment]
Gud stuff.

**Comment by yangshun** [comment]
Love that sarcasm :trollface:

**Comment by tgxworld** [comment]
So much wow!

**Comment by xinan** [comment]
Awesome one!

**Comment by yangshun** [comment]
You guys .... =___= have a look at my other (more) legit commits ok. Anws yay i fulfilled hacktoberfest requirements :stuck_out_tongue_closed_eyes:

**Pull request merged**
