### PR TITLE
Attempt to fix test times

### PR DESCRIPTION
**Pull request by li-kai**
Follows https://jestjs.io/docs/en/troubleshooting#tests-are-extremely-slow-on-docker-and-or-continuous-integration-ci-server

### CODE REVIEW

**Comment by li-kai** [comment]
Tests take 55s instead of 4min now.

**Comment by taneliang** [comment]
It doesn't look like anything changed though. The test part was previously 46 seconds on [this job](https://circleci.com/gh/nusmodifications/nusmods/9029#build-timing/containers/0).

**Comment by ZhangYiJiang** [comment]
is-ci is unnecessary to set explicitly - jest already sets it when it detects CI environment

**Comment by li-kai** [comment]
@taneliang At least the red bars from each individual test taking too long is removed.

Hoping this would solve random circleci problems we're seing.

**Pull request merged**
