### PR TITLE
[WIP] Indicate current timeslot on Timetable

### PR DESCRIPTION
**Pull request by zameschua**
### Motivation
This is a port from v2 where the current day would be highlighted on the timetable.
A new prop, `isCurrentDay`, is being passed to TimetableDay. (Uses Javascript `Date` object to calculate)

### Progress
Currently it looks like this
image

Works in vertical mode
image

Works in night mode as well
image

I aim to get it to look like this screenshot from @ZhangYiJiang but not sure what's the best way to insert the line indicator for the current time.
image

Also I'm trying to learn so let me know if there's anywhere to improve! 🙏

### CODE REVIEW

**Comment by yangshun** [comment]
Nice work! Note that this affects the exported timetable as it will contain the current day highlight also which is not ideal. cc #557

**Comment by taneliang** [comment]
Hey @zameschua, we're gonna integrate Prettier into our codebase very soon. Please chotto matte for a bit - once we're done with that we'll merge `master` into this branch for you.

**Comment by zameschua** [comment]
@taneliang ok got it!

**Comment by taneliang** [comment]
@zameschua Sorry I derped a bit there. Merged :)

**Comment by yangshun** [comment]
@zameschua Please delete your branch and checkout the branch again. I helped you resolved the merge conflicts and did a rebase (if not all the merge commits will show up here I think).

**Comment by zameschua** [comment]
I think I'm gonna re-clone the repo and re-open an issue because the removal of v2 made the files in the v3 folder disappear (??)

**Comment by ZhangYiJiang** [comment]
The files are in `www` - we just renamed the folder under the new structure

**Comment by yangshun** [comment]
Delete your local branch and checkout your fork's branch. We've updated your branch for you.

**Comment by zameschua** [comment]
I tried that but it was really weird, I couldn't switch branches because apparently I had made changes to my master (which I didn't) and I couldn't stash the changes as well haha

**Pull request closed without merging**
