### PR TITLE
Scrolls to top once view changes

### PR DESCRIPTION
**Pull request by xbili**
For issue [#38].

Scrolls to the top every time a new module page initializes. 

[#38]: https://github.com/nusmodifications/nusmods/issues/38

### CODE REVIEW

**Comment by yangshun** [comment]
Hey nice work! But scrolling to the top breaks the anchor tag behaviour. Go to [/ACC1006#prerequisites] (/ACC1006#prerequisites) for example. The normal case should look something like: 

screen shot 2015-01-02 at 1 22 02 am

**Comment by yangshun** [comment]
One workaround would be to check for existence of a hash fragment in the URL before executing the scrolling.

**Comment by xbili** [comment]
Right, I didn't take that into account, thanks! This should work now.

**Comment by yangshun** [comment]
Thanks a lot! :+1:

**Comment by yangshun** [comment]
I really like the idea of using animated scrolling. Feels very fluid!

**Comment by xbili** [comment]
Welcome! :D

**Pull request merged**
