### PR TITLE
Modifications to make Windows development environment setup easier

### PR DESCRIPTION
**Pull request by Yunheng**
Utilizes a modified version of the script from https://github.com/geerlingguy/JJG-Ansible-Windows to make setup easier for developers on Windows.

Windows setup only requires calling "vagrant up" and no need for "pip install ansible"

### CODE REVIEW

**Comment by yangshun** [comment]
Who has a Windows VM and is able to try this? >_<

**Comment by yangshun** [comment]
Hi @Yunheng , you can actually modify the git commit history for this branch and do away with the two revert commits. Simply git reset then commit again and force push to the branch. It's confusing to see a Revert Revert.

**Comment by Yunheng** [comment]
Hi @yangshun, oooh, didn't know that. Done!

**Comment by yangshun** [comment]
You didn't have to close it >_< If you change history and force push, this PR will be updated with your new commits.

**Comment by Yunheng** [comment]
Github closed it automatically after I force-pushed :(

**Comment by yangshun** [comment]
Hmm that's strange... Haha anyways just open a new PR then.

**Pull request closed without merging**
