### PR TITLE
Change background color for timetable filters

### PR DESCRIPTION
**Pull request by xbili**
For issue [#182](https://github.com/nusmodifications/nusmods/issues/182).

Made use of parent child selector to make the timetable filter buttons more intuitive. Let me know if it breaks anything! :)

### CODE REVIEW

**Comment by yangshun** [comment]
Thanks @xbili , can add some screenshots? :3

**Comment by xbili** [comment]
@yangshun This is what it looks like right now: 
screen shot 2015-05-12 at 11 15 02 pm
(Code, Room and Week are selected)

I'll look into using `pagination` instead, but it seems a bit odd to have a `pagination` for the filters. Some resizing has to be done too.

**Comment by yangshun** [comment]
Ah great. It looks good haha. If pagination cannot be used, then we'll stick to this. One minor modification: remove the drop shadows inside the selectors. We are going flat X)

**Comment by xbili** [comment]
@yangshun Yup done! :) 
screen shot 2015-05-12 at 11 32 01 pm

**Comment by yangshun** [comment]
Ok can merge. Please merge and file an issue to combine the timetable display filter and semester selector classes together lol.

Closes #182

**Pull request merged**
