### PR TITLE
Update to 2016

### PR DESCRIPTION
**Pull request by yangshun**
To be merged and deployed at 1st Jan 2016 0000 hrs. cc @xinan

### CODE REVIEW

**Comment by yangshun** [comment]
ROFL. that's hilarious

**Comment by xinan** [comment]
Can merge first, then deploy later :trollface:

**Comment by yangshun** [comment]
Ok thanks ah, rmb to deploy (:

**Comment by xinan** [comment]
Added cron task, see if it works. :trollface:

**Comment by yangshun** [comment]
Ok will check and let you know. I wonder if this is considered overengineering :joy:

**Comment by tgxworld** [comment]
confirm overengineering!

**Comment by yangshun** [comment]
It's updated :O Good job @xinan !

**Comment by tgxworld** [comment]
Omg you actually checked!

**Pull request merged**
