### PR TITLE
Allow ElasticSearch to be skipped on develop

### PR DESCRIPTION
**Pull request by ZhangYiJiang**
## Context

With the new ES persist code in #2020, it's now pretty difficult to run the code locally without spinning up an ES server. This PR skips the ES config check if the env is not production (ES is still used if it is available, but the code will now fall back to filesystem only if not)

### CODE REVIEW

**Comment by li-kai** [comment]
@taneliang Do we want to add back local elasticsearch w/ docker that would make this less painful?

**Comment by li-kai** [comment]
@taneliang Do we want to add back local elasticsearch w/ docker that would make this less painful?

**Comment by ZhangYiJiang** [comment]
Regardless of that we should still make it easy (easier?) to run the scraper without ES

**Comment by li-kai** [comment]
Could we use an environment variable like `SEND_ELASTICSEARCH` instead? By default it will be false so we can run it in dev if we want?

**Comment by ZhangYiJiang** [comment]
Isn't the config the same as using an env variable?

**Comment by li-kai** [comment]
Guess I wasn't looking at this very closely. You're right, it does. Could we highlight this in the README?

**Pull request merged**
