### PR TITLE
Add Telegram Channel to footer and FAQ page

### PR DESCRIPTION
**Pull request by Unknown15082**
## Context

Resolving issue #3790.

## Implementation

Added a Telegram link to the footer. Also add the link to the bottom of the FAQ page where people can reach NUSMods through various ways.

Footer:
image

FAQ page:
image

### CODE REVIEW

**Comment by ravern** [comment]
Thank you for your contribution!

Think you've ran into some conflicts, we'll review your PR after you resolve them. Looks good so far though!

**Review by kokrui — CHANGES_REQUESTED** [review]
As per @ravern's comments, do fix the merge conflict! But I'm otherwise happy with the changes

**Comment by Unknown15082** [comment]
I fixed the merge conflicts now, so please review my PR again. Thank you very much!

**Review by Unknown15082 — COMMENTED** [review]
Resolved the merge conflict.

**Review by ravern — APPROVED** [review]
LGTM

**Comment by zwliew** [comment]
Thank you!

**Pull request merged**
