### PR TITLE
Update checkPrerequisite to match wildcard prerequisites

### LINKED ISSUE #3733: Course Planner - Does not recognise prerequisite
### Describe the bug

An NUSC course has a prerequisite of any NTW-coded course, but does not reflect the prerequisite being cleared despite an NTW-coded module being taken earlier in the course plan

### To Reproduce

1. Select any NTWxxxx course in Y1 in the course planner
2. Select any NHSxxxx course in Y2 in the course planner

### Expected behavior

The NHS course should not be yellow, and should reflect the prerequisite being cleared

### Screenshots

image

### Desktop (please complete the following information):

- OS: Windows 11 Pro v. 23H2
- Browser: Chrome
- Version 125.0.6422.142

### Additional context

There are various NTW coded modules, any of which can clear the prerequisite for any of the NHS modules.

### PR DESCRIPTION
**Pull request by ChillinRage**
Change checking to parse for wildcards and check for matching prefixes instead of exact string matches.

## Context

Proposal to fix #3733 where prerequisite wildcards returns zero matches.

## Implementation

Changed the `checkPrerequisite` function in `planner.ts` to check if any module in the set has a prefix that matches the string before the wildcard symbol (i.e. UTC  in UTC%). 

The implementation is still the same as before for non-wildcard modules.

## Other Information

- `package.json` was updated as the previous version raised an error regarding outdated jest environ version when running `yarn test`.
- Updated `planner.test.ts` file to handle tests for wildcard modules.
- This is my first time committing to nusmods :)

### CODE REVIEW

**Review by ravern — COMMENTED** [review]
Welcome to NUSMods! Thanks for your first contribution :)

Overall, your code looks good, and it's awesome that you've updated the tests.

I checked out why your build is failing — it was originally due to a `yarn.lock` issue that I fixed on your branch. Just remember to run `yarn install` after editing `package.json`.

Now it's failing due to linter errors — there's some extra whitespace and you've used the wrong quotes for the `MODULE_WILD_CARD`. You can get the full list of errors by running `yarn lint`, or installing the ESLint plugin into your VS Code.

Once you get your build working, we should be good to go!

Here's a sample of the errors I get on your branch when running `yarn lint`:

image

I pushed a commit to your branch, so please run `git pull` before making any changes (apologies for this, I misjudged and thought it was a quick fix).

**Comment by ChillinRage** [comment]
Hi sorry for the late response. I have fixed the linter errors and warnings already. One question I have is why are iterative functions (like forEach, filter etc.) preferred over for loops?

**Comment by ravern** [comment]
Thank you for your fixes! And no need to apologise on response time, there's no rush on fixes/features :)

> One question I have is why are iterative functions (like forEach, filter etc.) preferred over for loops?

Unfortunately I don't have a good reason for you, since this is just part of the linting configuration we're using — we didn't explicitly opt-in to avoiding `for of` loops.

There's some discussion at https://github.com/airbnb/javascript/issues/1271 about why this rule exists, but I personally don't think there's a lot of productive discussion and it's really more of an opinion.

I would advise to just follow the linting configuration for now, unless it is obviously wrong/broken, in which case you can raise it up in your PR description for your reviewers.

**Review by ravern — APPROVED** [review]
LGTM!

**Comment by ravern** [comment]
You'll see your change in https://latest.nusmods.com, and we'll update once it's on https://nusmods.com (when we merge to `production` branch). Congrats on your first contribution @ChillinRage!

**Pull request merged**
