### PR TITLE
Timetable sharing

### PR DESCRIPTION
**Pull request by ZhangYiJiang**
This PR brings timetable sharing to v3. Compared to v2, it uses a more compact notation for encoding lessons - 

```
timetable/sem-1?CS2104=LEC:1,TUT:2&CS2105=LEC:1,TUT:1&CS2107=LEC:1,TUT:7&CS4212=LEC:1,TUT:1&CS4243=LAB:2,LEC:1
```

it uses a comma separated list of lessons, with each lesson being a key-value pair delimited by a colon. The features for this PR are

- Semester is now encoded in timetable URL 
- Timetable state is now encoded in URL 
- Timetable can be imported *if* there is no existing timetable 

Under the hood changes for this PR 

- Routes now goes under their own folder, with a `path.js` file that contains methods to help generate paths 
- `TimetableContainer` has been moved to `TimetableContent`, and `TimetableContainer` is now a wrapper component that now handles semesters and loads imported timetables. Unfortunately this makes the diff very messy. You may be better off reading the file directly. 

Features for future PRs include 

- Reduce amount of data encoded by dropping lessons with no alternatives 
- Add UI to let users overwrite existing timetables 
- Display a spinner while imported modules are being fetched 
- Validate imported modules and do not fetch invalid module codes

### CODE REVIEW

**Comment by ZhangYiJiang** [comment]
The best way to test this is to get the timetable URL, then open a private browsing window and paste that in to verify that the timetable is being imported correctly.

**Comment by yangshun** [comment]
Hmm I tested it in incognito with the following URL and it gives me a page not found error. Could it be because there no module data has been loaded? - http://localhost:8080/timetable/sem-1?ACC1002X=LEC:X1,TUT:X07&CS1010=SEC:2,TUT:C1B

**Comment by ZhangYiJiang** [comment]
This should be ready for review

**Comment by yangshun** [comment]
This PR is seriously too big to review. How about merge it and fix issues retroactively? 😎

**Comment by ZhangYiJiang** [comment]
Sorry about this - will make smaller PRs next time. Can you give a :+1: then? It's required for merging.

**Pull request merged**
