### PR TITLE
Fix striped tables in dark mode

### PR DESCRIPTION
**Pull request by angelsl**
### Before
[firefox_2017-04-21_23-46-09](https://nusmods.com/modules/GER1000)

### After
firefox_2017-04-21_23-46-21

### CODE REVIEW

**Comment by yangshun** [comment]
Thanks for this. Could you help to remove the JS that loads slate.min.css too?

**Comment by angelsl** [comment]
As far as I can tell... nothing actually loads it anymore. I'm not sure though.

**Comment by angelsl** [comment]
Oh, ok, I see it. Give me a moment.

**Comment by angelsl** [comment]
@yangshun That should be it.

**Comment by yangshun** [comment]
@angelsl Thanks so much. Are you an NUS student?

**Comment by angelsl** [comment]
@yangshun Next year. Currently looking for my pink IC. :)

**Pull request merged**
