### PR TITLE
Add Timetable Reset Button

### PR DESCRIPTION
**Pull request by EssWhyy**
## Context

Implements #3471 

## Implementation

Added a Reset Button to the timetable actions toolbar.
This button will prompt a popup modal asking if the user wishes to reset the timetable to an empty state.

Clicking said button will call removeModule() across all modules in the given timetable prop for the current semester, thereby removing all modules and restting the timetable. resetTombstone() is also called once to remove the last module tombstone.

Video of UI and functionality:

https://github.com/nusmodifications/nusmods/assets/39799639/37cb1b9c-3da1-4fdf-87f9-b98bdac12915

### CODE REVIEW

**Review by joeng03 — COMMENTED** [review]
Great work overall! Apart from the nits I pointed out, I do think that adding an additional reducer for resetModules() will be slightly better for performance than calling removeModule() in a for loop. Do refer to https://github.com/joeng03/nusmods/tree/issue-3471-timetable-reset?tab=readme-ov-file for the implementation!

**Comment by EssWhyy** [comment]
@joeng03 Thanks for the feedback. I was gonna work on refactoring it based on your suggestions but I see that you have already merged and implemented the improvements in your own branch above? I’ll leave you to merge it on your end then

**Comment by joeng03** [comment]
I have opened the PR at #3646. Please help review and merge it

**Comment by zwliew** [comment]
Thanks for this; I'll close this PR and review just #3646.

**Pull request closed without merging**
