### PR TITLE
Update renovate config

### PR DESCRIPTION
**Pull request by li-kai**
According to renovate's docs, their bot should have triggered on #1552 and told us if the config was valid, but it didn't. So here's another attempt to triggering it.

Docs: https://renovatebot.com/docs/reconfigure-renovate/

### CODE REVIEW

**Comment by ZhangYiJiang** [comment]
Hmmm, maybe we can try setting `@types` to autoupdate?

**Comment by li-kai** [comment]
@ZhangYiJiang I don't see how we can make `@types` auto merge while keeping them in step with our actual dependencies at the same time.

**Comment by ZhangYiJiang** [comment]
The problem I see now is that we get spammed with a ton of `@types` updates since typedefs can change more frequently than the actual packages, especially for larger packages. It's also relatively safe to merge in libdefs if CI is green, and we can't effectively review the PRs for `@types` because there's no changelog and the source link doesn't even link to the correct subdirectory in the repo. Automerging the `@types` changes is meant to solve this, but there might be other solutions I've not thought of.

**Comment by li-kai** [comment]
I've added a `@types` group which excludes ones that are already grouped. This should automerge types and other groups if all the tests pass.

**Pull request merged**
