### PR TITLE
Add Dark Mode toggle to Settings page

### PR DESCRIPTION
**Pull request by yangshun**
screen shot 2017-12-11 at 11 21 32 pm

### CODE REVIEW

**Comment by ZhangYiJiang** [comment]
I think calling it 'Night Mode' or 'Dark theme' with an on/off toggle would be clearer 

eg. YouTube's 

screenshot from 2017-12-12 15-24-47

**Comment by yangshun** [comment]
What app is that?

**Comment by yangshun** [comment]
Not inclined to use theme again because we're already using it for the timetable colors.

**Comment by ZhangYiJiang** [comment]
That's YouTube's website. If you're logged in, the option is under your user's icon on the top right hand corner under 'dark theme'

**Pull request merged**
