### PR TITLE
Add .travis.yml

### PR DESCRIPTION
**Pull request by ngzhian**

### CODE REVIEW

**Comment by ngzhian** [comment]
So travis fails due to lint issues (and others), the fix to make it green (or less red) will come in other PRs

**Comment by tgxworld** [comment]
It is fine to include the fixes for lint in this PR. Just separate them into different commits.

**Comment by 9gix** [comment]
@ngzhian would be good to have this [Build Status](https://travis-ci.org/nusmodifications/nusmods) badge included in the README.md.

:sunglasses:

**Comment by ngzhian** [comment]
@9gix great idea, and I really want it to be green before I put it there :)

**Comment by ngzhian** [comment]
Fixes #255

**Pull request merged**
